WITH BOOK_SALES_2022_1 AS(
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
),

BOOK_AUTHOR AS(
    SELECT *
    FROM BOOK INNER JOIN AUTHOR USING(AUTHOR_ID)
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((PRICE * SALES)) TOTAL_SALES 
FROM BOOK_AUTHOR A INNER JOIN BOOK_SALES_2022_1 S USING(BOOK_ID)
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC