WITH MY_CART AS (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS C1
    WHERE EXISTS(
        SELECT 1
        FROM CART_PRODUCTS C2
        WHERE C1.CART_ID = C2.CART_ID AND NAME = 'Milk'
    ) AND
        EXISTS(
            SELECT 1
            FROM CART_PRODUCTS C2
            WHERE C1.CART_ID = C2.CART_ID AND NAME = 'Yogurt'
        )
)

SELECT CART_ID 
FROM MY_CART
GROUP BY CART_ID
ORDER BY 1