WITH RECURSIVE CTE1 AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, GENERATION + 1 AS GENERATION
    FROM CTE1 C INNER JOIN ECOLI_DATA E ON C.ID = E.PARENT_ID
)

SELECT ID
FROM CTE1
WHERE GENERATION = 3
ORDER BY 1