WITH ON_3 AS(
    SELECT SALES_DATE, USER_ID, PRODUCT_ID, SALES_AMOUNT, 'ON' SALES_TYPE
    FROM ONLINE_SALE
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '3'
),

OFF_3 AS(
    SELECT SALES_DATE, PRODUCT_ID, SALES_AMOUNT, 'OFF' SALES_TYPE
    FROM OFFLINE_SALE
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '3'
),

TOTAL_3 AS(
    SELECT SALES_DATE, USER_ID, PRODUCT_ID, SALES_AMOUNT, 'ON' SALES_TYPE 
    FROM ON_3
    UNION
    SELECT SALES_DATE, NULL USER_ID, PRODUCT_ID, SALES_AMOUNT, 'OFF' SALES_TYPE
    FROM OFF_3
)

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM TOTAL_3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID