WITH OUTS_YES AS(
    SELECT ANIMAL_ID, NAME, DATEDIFF(O.DATETIME, I.DATETIME) + 1 DAYS
    FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O USING(ANIMAL_ID, ANIMAL_TYPE, NAME)
    WHERE O.DATETIME IS NOT NULL
    ORDER BY DAYS DESC
)

SELECT ANIMAL_ID, NAME FROM OUTS_YES
LIMIT 2