WITH TARGET_INFO AS (
    SELECT CAR_ID, DAILY_FEE, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C 
    WHERE CAR_TYPE IN ('세단', 'SUV') AND NOT EXISTS(
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.CAR_ID = C.CAR_ID AND
        START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
),

TARGET_DIS AS (
    SELECT CAR_TYPE,
    CAST(SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS UNSIGNED) DURATION_TYPE,
    1 - (CAST(SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS UNSIGNED) * 0.01) DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE = 30
)

SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * 30 * DISCOUNT_RATE, 0) FEE
FROM TARGET_INFO I INNER JOIN TARGET_DIS D USING(CAR_TYPE)
WHERE ROUND(DAILY_FEE * DURATION_TYPE * DISCOUNT_RATE, 0) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC