SELECT T.ID, 
    CASE 
        WHEN T.COLONY_NAME = 1 THEN 'CRITICAL'
        WHEN T.COLONY_NAME = 2 THEN 'HIGH'
        WHEN T.COLONY_NAME = 3 THEN 'MEDIUM'
        WHEN T.COLONY_NAME = 4 THEN 'LOW'
    END COLONY_NAME    
FROM (
    SELECT *, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NAME
    FROM ECOLI_DATA
) T
ORDER BY T.ID