WITH NTILE_TABLE AS (
    SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) AS COLONY_RANK
    FROM ECOLI_DATA
)

SELECT ID,
    CASE 
        WHEN COLONY_RANK = 4 THEN 'CRITICAL'
        WHEN COLONY_RANK = 3 THEN 'HIGH'
        WHEN COLONY_RANK = 2 THEN 'MEDIUM'
        WHEN COLONY_RANK = 1 THEN 'LOW'
    END COLONY_NAME
FROM NTILE_TABLE N
ORDER BY ID