WITH INTAKE_NO AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE ('Intact%')
),

OUTCOME_YES AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_OUTCOME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE ('Spayed%') OR SEX_UPON_OUTCOME LIKE ('Neutered%')
)

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM INTAKE_NO I INNER JOIN OUTCOME_YES O USING(ANIMAL_ID, ANIMAL_TYPE, NAME)
ORDER BY 1, 2, 3