WITH SEOUL_REST AS (
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE('서울%')
),

TOTAL AS (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE
    FROM SEOUL_REST S INNER JOIN REST_REVIEW R USING(REST_ID)
    GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    ORDER BY SCORE DESC, FAVORITES
)

SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM TOTAL
WHERE (REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE) IN (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE
    FROM SEOUL_REST S INNER JOIN REST_REVIEW R USING(REST_ID)
    GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    ORDER BY SCORE DESC, FAVORITES
)
ORDER BY SCORE DESC, FAVORITES DESC