SELECT 
    YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH, 
    COUNT(DISTINCT I.USER_ID) PURCHASED_USERS, 
    ROUND(
        COUNT(DISTINCT I.USER_ID) * 1.0 / 
        (
            SELECT COUNT(DISTINCT USER_ID) 
            FROM USER_INFO 
            WHERE YEAR(JOINED) = 2021
        ),
        1
    ) PURCHASED_RATIO
FROM USER_INFO I INNER JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH