WITH JOINED_USER_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),

TARGET_SALES AS (
    SELECT USER_ID, SALES_DATE
    FROM ONLINE_SALE
    WHERE USER_ID IN (
        SELECT USER_ID FROM JOINED_USER_2021
    )
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM JOINED_USER_2021),1) AS PURCHASED_RATIO
FROM TARGET_SALES
GROUP BY 1,2
ORDER BY 1,2;