WITH RECURSIVE CNT_GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, C.GENERATION + 1
    FROM CNT_GENERATION C INNER JOIN ECOLI_DATA E ON C.ID = E.PARENT_ID
),

CHECK_PARENT AS (
    SELECT DISTINCT PARENT_ID ID
    FROM CNT_GENERATION
    WHERE PARENT_ID IS NOT NULL
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CNT_GENERATION
WHERE ID NOT IN (
    SELECT * FROM CHECK_PARENT
)
GROUP BY 2
ORDER BY 2