-- 코드를 입력하세요
SELECT DISTINCT CAR_ID, 
CASE WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE) = 1 THEN '대여중'
                ELSE '대여 가능'
    END AS AVAILAVILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC;