WITH OUTCOME_NO AS (
    SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME, I.DATETIME 'IN', O.DATETIME 'OUT'
    FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.DATETIME IS NULL
)

SELECT NAME, O.IN DATETIME 
FROM OUTCOME_NO O
ORDER BY 2
LIMIT 3