WITH HEAVY_HOST AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2
)

SELECT * 
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM HEAVY_HOST
)
ORDER BY 1