WITH ORDER_2022 AS (
    SELECT *
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '5'
),

TOTAL_PRICE AS (
    SELECT PRODUCT_ID, PRODUCT_NAME, SUM((PRICE * AMOUNT)) TOTAL_SALES
    FROM FOOD_PRODUCT P INNER JOIN ORDER_2022 O USING(PRODUCT_ID)
    GROUP BY PRODUCT_ID
)

SELECT PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES
FROM TOTAL_PRICE
WHERE (PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES) IN (
    SELECT PRODUCT_ID, PRODUCT_NAME, SUM((PRICE * AMOUNT)) TOTAL_SALES
    FROM FOOD_PRODUCT P INNER JOIN ORDER_2022 O USING(PRODUCT_ID)
    GROUP BY PRODUCT_ID
)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID