WITH TRUCK_INFO AS (
    SELECT CAR_ID, DAILY_FEE, HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 DAYS, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H USING(CAR_ID)
    WHERE CAR_TYPE = '트럭'
),

TRUCK_DIS AS (
    SELECT 
        CAR_TYPE,
        CAST(SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS UNSIGNED) DURATION_TYPE,
        CAST(SUBSTRING_INDEX(DISCOUNT_RATE, '%', 1) AS UNSIGNED) * 0.01 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT 
    HISTORY_ID, 
    ROUND(I.DAYS * I.DAILY_FEE * (1 - MAX(IFNULL(D.DISCOUNT_RATE, 0)))) AS FEE
FROM TRUCK_INFO I
LEFT JOIN TRUCK_DIS D
    ON I.DAYS >= D.DURATION_TYPE
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;