WITH APP_4_13 AS (
    SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID AS DR_ID
    FROM APPOINTMENT
    WHERE APNT_CNCL_YN = 'N' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND MCDP_CD = 'CS'
)

SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD 
FROM PATIENT P INNER JOIN APP_4_13 A USING(PT_NO) INNER JOIN DOCTOR D USING(DR_ID)
ORDER BY APNT_YMD