WITH COUNT_MEM AS (
    SELECT MEMBER_ID, MEMBER_NAME, COUNT(REVIEW_ID) COUNT
    FROM MEMBER_PROFILE P INNER JOIN REST_REVIEW R USING(MEMBER_ID)
    GROUP BY MEMBER_ID
),

BEST_MEM AS (
    SELECT *
    FROM COUNT_MEM
    WHERE COUNT = (SELECT MAX(COUNT) FROM COUNT_MEM)
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE 
FROM BEST_MEM B INNER JOIN REST_REVIEW R USING(MEMBER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT