WITH BOOK_SALES_2022_1 AS(
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
)

SELECT CATEGORY, SUM(SALES)
FROM BOOK B INNER JOIN BOOK_SALES_2022_1 S USING(BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY