SELECT CASE
    WHEN D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE('FRONT%')) && 
        D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON') THEN 'A'
    WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
    WHEN D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE('FRONT%')) THEN 'C'
    END GRADE,
    D.ID, D.EMAIL
FROM DEVELOPERS D, SKILLCODES S
GROUP BY GRADE, D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE